### ISSUE TITLE
Error: Unparsable version range: ">3.x"

### ISSUE THREAD

**Issue by tombmurphy** [Spantree/puppet-phpldapadmin#5] opened 2014-10-10 00:26 UTC
On CentOS or Red Hat 6.5 I get the following error when attempting to install the module:

puppet module install spantree/phpldapadmin
Notice: Preparing to install into /etc/puppetlabs/puppet/modules ...
Notice: Created target directory /etc/puppetlabs/puppet/modules
Notice: Downloading from https://forgeapi.puppetlabs.com ...
Error: Unparsable version range: ">3.x"
Error: Try 'puppet help module install' for usage

It works fine in Ubuntu/Debian.

**Comment by feniix** [comment] 2015-10-07 21:04
@tombmurphy do you still have this issue? I could not reproduce with puppet ce only with puppet pe but I do not use puppet enteprise. Can I close this?

**Comment by feniix** [comment] 2016-04-22 20:34
I am closing this issue because: 
```[root@9e57ac8e211a el-7-x86_64]# /opt/puppet/bin/puppet module install spantree/phpldapadmin
Notice: Preparing to install into /etc/puppetlabs/puppet/modules ...
Notice: Created target directory /etc/puppetlabs/puppet/modules
Notice: Downloading from https://forgeapi.puppetlabs.com ...
Notice: Installing -- do not interrupt ...
/etc/puppetlabs/puppet/modules
└─┬ spantree-phpldapadmin (v0.0.13)
  └── puppetlabs-stdlib (v4.5.1)
[root@9e57ac8e211a el-7-x86_64]# /opt/puppet/bin/puppet --version
3.8.5 (Puppet Enterprise 3.8.4)```

**Comment by feniix** [comment] 2016-04-22 21:09
also
```[root@e53cec9572dd el-6-x86_64]# /opt/puppet/bin/puppet module install spantree/phpldapadmin
Notice: Preparing to install into /etc/puppetlabs/puppet/modules ...
Notice: Created target directory /etc/puppetlabs/puppet/modules
Notice: Downloading from https://forgeapi.puppetlabs.com ...
Notice: Found at least one version of puppetlabs-stdlib compatible with PE (3.3.2);
Notice: Skipping versions which don't express PE compatibility. To install
the most recent version of the module regardless of compatibility
with PE, use the '--ignore-requirements' flag.
Notice: Installing -- do not interrupt ...
/etc/puppetlabs/puppet/modules
└─┬ spantree-phpldapadmin (v0.0.13)
  └── puppetlabs-stdlib (v4.5.1)
[root@e53cec9572dd el-6-x86_64]# /opt/puppet/bin/puppet --version
3.6.2 (Puppet Enterprise 3.3.2)
[root@e53cec9572dd el-6-x86_64]# cat /etc/redhat-release
CentOS release 6.7 (Final)```

**Closed by feniix** 2016-04-22 21:09 UTC
Labels: bug, confirmed
